# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 04:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170217_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='created',
        ),
        migrations.AddField(
            model_name='postlike',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(related_name='like_post_set', through='post.PostLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
